/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerateResumeRouteImport } from './routes/generate.resume'
import { Route as GenerateCoverLetterRouteImport } from './routes/generate.cover-letter'

const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateResumeRoute = GenerateResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => GenerateRoute,
} as any)
const GenerateCoverLetterRoute = GenerateCoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => GenerateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate': typeof GenerateRouteWithChildren
  '/generate/cover-letter': typeof GenerateCoverLetterRoute
  '/generate/resume': typeof GenerateResumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate': typeof GenerateRouteWithChildren
  '/generate/cover-letter': typeof GenerateCoverLetterRoute
  '/generate/resume': typeof GenerateResumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generate': typeof GenerateRouteWithChildren
  '/generate/cover-letter': typeof GenerateCoverLetterRoute
  '/generate/resume': typeof GenerateResumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generate' | '/generate/cover-letter' | '/generate/resume'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generate' | '/generate/cover-letter' | '/generate/resume'
  id:
    | '__root__'
    | '/'
    | '/generate'
    | '/generate/cover-letter'
    | '/generate/resume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateRoute: typeof GenerateRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/resume': {
      id: '/generate/resume'
      path: '/resume'
      fullPath: '/generate/resume'
      preLoaderRoute: typeof GenerateResumeRouteImport
      parentRoute: typeof GenerateRoute
    }
    '/generate/cover-letter': {
      id: '/generate/cover-letter'
      path: '/cover-letter'
      fullPath: '/generate/cover-letter'
      preLoaderRoute: typeof GenerateCoverLetterRouteImport
      parentRoute: typeof GenerateRoute
    }
  }
}

interface GenerateRouteChildren {
  GenerateCoverLetterRoute: typeof GenerateCoverLetterRoute
  GenerateResumeRoute: typeof GenerateResumeRoute
}

const GenerateRouteChildren: GenerateRouteChildren = {
  GenerateCoverLetterRoute: GenerateCoverLetterRoute,
  GenerateResumeRoute: GenerateResumeRoute,
}

const GenerateRouteWithChildren = GenerateRoute._addFileChildren(
  GenerateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateRoute: GenerateRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
